### ISSUE TITLE
UglifyJS error when running `to-es5` script

### ISSUE THREAD

**Issue by nicodn** [loadimpact/k6-hardware-benchmark#1]
I'm getting errors with the sample `to-es5` script:
```
ERROR in k6_load_script.es5.js from UglifyJs Unexpected token: keyword «const» ...
```

Any clues as to how to fix this?

**Comment by nicodn** [comment]
I got past this issue with `forceAllTransforms`
https://babeljs.io/docs/en/babel-preset-env#forcealltransforms

**Comment by mhubig** [comment]
@nicodn where dit you put this option? I put it within the babelrc but it didn't help ...

**Comment by nicodn** [comment]
I put it in my `webpack.config.js`:

```
module: {
    rules: [
      {
        use: [
          {
            loader: 'babel-loader',
            options: {
              presets: [['@babel/preset-env', {
                forceAllTransforms: true,
//...
```
